server:
  port: 10001

spring:
  application:
    name: cdi-mmp-doctor
  profiles:
    active: dev

--- # nacos 配置
spring:
  cloud:
    inetutils:
      preferred-networks: 192.168
      ignored-networks: 169.254,100.91
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
        # 指定注册 IP，避免使用 Tailscale 分配的 IP
        ip: 192.168.1.45  # 替换为你的实际本机 IP
      config:
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
